### ISSUE TITLE
please try following for a working version of within

### ISSUE THREAD

**Issue by ghost** [sivnz/codeceptjs#1]
I couldnt test it in my PC as there is some issue of electron in windows.
`
Feature('Testing Example Feature');

Scenario('test something', (I) => {
    I.amOnPage('https://www.w3schools.com/html/html_iframe.asp');
    I.seeInTitle('Iframes');
    //I.amOnPage('https://www.w3schools.com/html/html_iframe.asp') 
    within('a[href*=\'html_quiz.asp\']', function(){
        I.click('Start HTML Quiz!')
    },['iframe[src*=\default.asp\'']);
    ;    
});
`

**Comment by andreluizbnu** [comment]
It worked.
All good!
